version: "3.8"

services:
  assistants-budget-api-prod:
    image: lednev/assistants-budget-api:production
    container_name: assistants-budget-api-prod
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"
    networks:
      - assistants-budget

  assistants-budget-ui-prod:
    image: lednev/assistants-budget-ui:production
    container_name: assistants-budget-ui-prod
    build: ./assistants-budget-ui
    ports:
      - "80"
    networks:
      - assistants-budget

networks:
  assistants-budget:
    external: true
