version: "3.8"

services:
  jenkins:
    image: assistants-budget.jenkins
    build:
      context: .
      dockerfile: ./jenkins/Dockerfile
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: assistants-budget.jenkins
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - assistants-budget

  sonarqube:
    image: sonarqube:lts
    container_name: assistants-budget.sonarqube
    ports:
      - 9000:9000
    volumes:
      - ./sonar/data:/opt/sonarqube/data
      - ./sonar/logs:/opt/sonarqube/logs
      - ./sonar/extensions:/opt/sonarqube/extensions
      - ./sonar/conf:/opt/sonarqube/conf
      - ./sonar/temp:/opt/sonarqube/temp
      - ./sonar/bundled_plugins:/opt/sonarqube/lib/bundled-plugins
    environment:
      # - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
      # - SONAR_JDBC_USERNAME=${POSTGRES_USER}
      # - SONAR_JDBC_PASSWORD=${POSTGRES_PASS}
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    networks:
      - assistants-budget

networks:
  assistants-budget:
    external: true
