version: "3.8"

services:
  assistants-budget-api-dev:
    image: lednev/assistants-budget-api:development
    container_name: assistants-budget-api-dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"
    networks:
      - assistants-budget

  assistants-budget-ui-dev:
    image: lednev/assistants-budget-ui:development
    container_name: assistants-budget-ui-dev
    build: ./assistants-budget-ui
    ports:
      - "80"
    networks:
      - assistants-budget

networks:
  assistants-budget:
    external: true
