version: "3.8"

services:
  nginx:
    image: nginx:1.21.3-alpine
    container_name: assistants-budget.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/config:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/ssl/private:ro
      - ./nginx/ssl/.well-known:/etc/nginx/.well-known:ro
    networks:
      - assistants-budget

networks:
  assistants-budget:
    external: true
