name: Assistants. Budget - UI

on:
  push:
    branches: ["develop", "main"]
    paths:
      - "assistants-budget-ui/**"
      - "!**/README.md"
      - "!**/gitignore"
      - "!**/.husky/**"
      - "!**/.vscode/**"
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        options:
          - "develop"
          - "production"

permissions:
  id-token: write
  contents: read

jobs:
  prepare:
    name: "Prepare project for build"
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ./assistants-budget-ui/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install
        working-directory: ./assistants-budget-ui

  build:
    name: "Build and Deploy UI to S3"
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: prepare
    defaults:
      run:
        working-directory: .

    steps:
      - name: Deploy to S3
        uses: ./actions/react-deploy-to-s3
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          NODE_ENV: production # optional: defaults to production
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-1 # optional: defaults to us-east-1
          SOURCE_DIR: ./assistants-budget-ui/build # optional: defaults to public
          WORKING_DIRECTORY: ./assistants-budget-ui
